require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/LineLength:
  Max: 100
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Layout/LineContinuationLeadingSpace:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Metrics/ClassLength:
  Max: 300
Metrics/ModuleLength:
  Max: 300
Performance/RedundantBlockCall:
  Enabled: false
Style/DateTime:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
Gemspec/DevelopmentDependencies:
  Enabled: true
Gemspec/DeprecatedAttributeAssignment:
  Enabled: true
Rails/I18nLocaleTexts:
  Enabled: false
